### ISSUE TITLE
Get purchases for yesterday total amount is wrong

### ISSUE THREAD

**Issue by Mat-Moo** [bendudz/fpp-zettle#1]
Looking at the code, I think your missing the endDate parameter for this request (think should be the same as startDate - so the yesterday totals include todays totals as well.

**Comment by PiSignage** [comment]
Thank you for pointing this out. You are rights about missing endDate. A update will be pushed out tonight fixing this issue and some other little fixs

**Comment by Mat-Moo** [comment]
No worries, just so excited to use it and realised the totals didn't tally... and as a dev, I like to poke :)

**Comment by PiSignage** [comment]
I have just update the code to fix yesterday totals
