### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by Mat-Moo** [bendudz/fpp-zettle#2]
Thanks for fixing the yesterday total, but now I'm hitting Update now, it runs some bits....

`Running install script /home/fpp/media/plugins/fpp-zettle/scripts/fpp_install.shInstalling Announce Zettle Plugin for FPP....
Writing config file....
 Config file exists and is not empty... continuing 
You need a secure https endpoint on your pi to use this plugin. Dataplicity is the easiest way to achieve that. Check out the readme or the plugin help text for more information.

Done`

And then when I close and refresh it still asks for an update

P.s
not sure the echo should of been in the previous push?
```
<?php
echo isSiteAvailible(str_replace('/api/plugin/fpp-zettle/event', '', $pluginJson['subscriptions'][0]['destination']));
if (isSiteAvailible(str_replace('/api/plugin/fpp-zettle/event', '', $pluginJson['subscriptions'][0]['destination'])) !== 200) {
    echo '<div class="alert alert-danger">FPP could not be seen, have you actived wormhole on dataplicity</div>';
}
?>
```
If it was then
```
<?php
$isSiteAvailable = isSiteAvailible(str_replace('/api/plugin/fpp-zettle/event', '', $pluginJson['subscriptions'][0]['destination']))
echo $isSiteAvailable;
if ($isSiteAvailable !== 200) {
    echo '<div class="alert alert-danger">FPP could not be seen, have you actived wormhole on dataplicity</div>';
}
?>
```
and technically the function should define the return type :) but that's my dev hat on - happy to help if needed

**Comment by PiSignage** [comment]
Hi Mat,

I am glad the totals workout right now. The echo $isSiteAvailable is not spose to be there. My error I will remove it.

The update now button is something I was trying. I think that is going to be removed also. The docs for fpp plugin is every minimal. So it a lot of trial and error.

**Comment by Mat-Moo** [comment]
If you need any help, I’m happy to code review or help etc.

**Comment by PiSignage** [comment]
Hi Mat,
I have removed the echo and the update now buttons as there seems to be a problem it. Fell free to do a pull request

**Comment by Mat-Moo** [comment]
Still asks me to update?

**Comment by PiSignage** [comment]
Hi Mat,. Run the update from the plugin list. I have removed the update button from the plugin page as it don't seem to be working.

**Comment by Mat-Moo** [comment]
Tried it everywhere, still says update :( grrr maybe I'll try command line, or have to uninstall and reinstall it

**Comment by PiSignage** [comment]
I don't know the command you would need to use in the command line. If you uninstall and reinstall that should fix the problem. But your config details will be deleted on uninstall. You would need to recreated api keys
