### ISSUE TITLE
Lost connection

### ISSUE THREAD

**Issue by Mat-Moo** [bendudz/fpp-zettle#5]
I've had a look through the API and can't see anything obvious - but on Christmas Eve my phone lost connection to the internet, and consequently tap to donate failed after 1 payment :( I've been trying to figure out how to poll/check things are still connected - So this is more an chat than issue.

It's easy enough to find the IP of the phone, so could ping it once a minute to see if at least it still is attached to the internet? But that wouldn't mean the reader is attached to the phone. - 

Thoughts?

**Comment by PiSignage** [comment]
You are right that there is no way to detect if the card reader has lost connection to the phone and there is no way to detect a failed payment. I had the reader disconnect from the phone a number of times over December. I did add a heat pad to the reader box that helped but did not fully. I moved the phone closer that did help. The phone was 10 feet away it seemed stable.

With the phone discontinuing from the Internet you could ping it every minute as you said then maybe send out an alert. Maybe a custom app could detect if the reader is not connected but i don't know. I could look at the ios docs and see if that is the cases or not. 

For the moment there is not much that can be done without keep checking

**Comment by Mat-Moo** [comment]
Mine seems to be the phone losing signal, which is odd as never had an issue last year - Maybe I'll just put a ping in place, as if you can't ping the phone it can't process a payment.
