### ISSUE TITLE
Getting more info into the MQTT or URL commands?

### ISSUE THREAD

**Issue by degracode** [bendudz/fpp-zettle#6]
It doesn't appear that any of the Commands (except for Overlay Model Effect) can provide metadata about the transaction.
For example encoding amount or total information via the MQTT or URL commands, which could then allow the information to be responded to more uniquely (eg based on the amount, or current total), or simply logged for record-keeping.

Could some facility for this be added to `runCommand`?
https://github.com/bendudz/fpp-zettle/blob/7b02d8315ef0402c63534db1e9f99039233cf9e0/api.php#L297

Eg the URL command could also run through `buildMessage` to do some find and replace
http://myserver/zettle/transaction?amount={{AMOUNT}}&total={{EVERYTHING}}

**Comment by PiSignage** [comment]
I have just merged your pull request.
